default: demo1 demo2 demo3
demo1: demo1.c libmemlab.a
	g++ -o demo1 demo1.c libmemlab.a -pthread
demo2: demo2.c libmemlab.a
	g++ -o demo2 demo2.c libmemlab.a -pthread
demo3: demo3.c libmemlab.a
	g++ -o demo3 demo3.c libmemlab.a -pthread
clean:
	rm -f demo1 demo2 demo3
